services:
  db:
    image: postgres:16
    container_name: postgres_superstore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: superstore
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
